### PR TITLE
Odd lots tender feature

### PR DESCRIPTION
**Pull request by dimjava**
1) Add voluntary offer allocation for odd lots tender

    This corporate action occurs with tender action. See xml example: [odd-lot.txt](https://github.com/titov-vv/jal/files/8102588/odd-lot.txt).

    There may be other types of offer allocations possible (for example partial one), but I don't have xml examples of how IB represents them. So I added most specific regex to parse such trades, to avoid incorrect processing.

2) Auto load portfolio currencies from CBR

### CODE REVIEW

**Comment by titov-vv** [comment]
Hi!
Thanks a lot for the example and ideas. I'll review, add test case and then merge it into master for next release.

**Comment by titov-vv** [comment]
Could you please help me to validate my understanding.
Did I get it right from company website - it was some kind of buyback operation? And as a result - normal stock CORT had been converted to CORT.OD2 and then these new stocks were boutgh at fixed price $20.75 per shared. Right?
Was there any voting before to choose number of shares? I see there was some kind of subscription but don't know what kind of choice you really had. Was it possible to keep some part of shares and sell only another part?

**Comment by dimjava** [comment]
> it was some kind of buyback operation? And as a result - normal stock CORT had been converted to CORT.OD2 and then these new stocks were boutgh at fixed price $20.75 per shared. Right?

Right. But it was special case named "odd lot": company buys out small shareholders (under 100 shares).

> Was it possible to keep some part of shares and sell only another part?

There was an option to submit any number of shares you have, but "odd lot" applies only for 99 and less.
Even more, for example, there was one more case like that with CFF (TSX exchange) with option to get money in USD or in CAD.


By the way, ordinary voluntary buyout looks like that 

`CRN.SUB6(AU026122SUB6) Merged(Voluntary Offer Allocation) WITH AU0000026122 1 FOR 1 (CRN, CORONADO GLOBAL RESOURCE-CDI, AU0000026122)`

and your regex doesn't cover it. The problem is in spaces in "Voluntary Offer Allocation", but regex uses "\w+"

**Comment by dimjava** [comment]
Seems CRN case is some other kind of corp action, will be back to clarify.

**Comment by titov-vv** [comment]
Thanks.

> There was an option to submit any number of shares you have  

This I think may require one more correction. I'll check.
> The problem is in spaces in "Voluntary Offer Allocation", but regex uses "\w+"

Yes, I haven't seen such descriptions with spaces before so made it strict to letters only.
> Even more, for example, there was one more case like that with CFF (TSX exchange) with option to get money in USD or in CAD.

Yes, this one may be a problem if you bought security with USD, for example, and then company bought it back for CAD. I'm working right now to change assets table and handle multiple symbols/currencies per security. Then I think it should be possible to implement.

**Comment by dimjava** [comment]
Situation with CRN is [rights subscription offer](https://www.investopedia.com/terms/r/rightsoffering.asp#:~:text=In%20a%20rights%20offering%2C%20the,them%20in%20the%20open%20market.).

**Comment by titov-vv** [comment]
Sorry for late update but situation with Ukraine delays everything.
I reviewed your code once more, made small changes and updated test cases. 
Thanks again for your help.

**Pull request merged**
